AllCops:
  Exclude:
    - 'vendor/**/*'
  DisplayCopNames: true
Rails:
  Enabled: true
Layout/SpaceInsideBlockBraces:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Layout/EmptyLines:
  Enabled: false
Metrics/LineLength:
  Enabled: false
