language: ruby
rvm:
- 2.6.3
script: rake
notifications:
  slack:
    secure: cmaqz5XhMohlP4o5ZertyvRa4TIGLSOCwrm06QwkpJQlK1tVNbqdHlhV/qIU8tio1HYw6+I92lCMeCJaqOWCxoXrvqktN10QnBjXjgufLoIRdcFSnxcgqDq8vJpsUbRvvTEw6hvtho0Og/O7rPcTQ5tFZ+oFAnzDd4+bx+F3p2NcC07KxPge+MsIhG+P/AKW4JmNkuHq51wQ3oM3+EbmRj5AaKpPzY7vmJT8fNKSgymtp72pTyzAYLy3LRPY7M/ipbQFrY8pLT8saVeLjcaUnGoCn+BYPisJohUVBOHGHRHrJMtK6bS8K7IvlOmHWwi5DoeKgrYjgZ/L7pJO/n4d0PK117ys5xRr4gshaYin5Rlc4M89YxPWJf/qcsM+aOvNKwE/RWI3vJYDPRLTRSJVP9hKlikgUaibnsOkThQ7BAsI5YIKw/o9kyka/HfaxigbrQof6KcMadyMJc6P1j7hU30gjUZKWmoQF4rij7d+lvMkTLcf6k3KIFlm3qwaOVvlqA6flZuCArkW064BqN1YsbW83GlmsBPp6HsJNBaI+SZOVkXiVgABhjABVOlKvPuglKnF3yNdSQJeG4Fq7CLzGwYuOnlTC2mzLe2Z6wudY720pUIMh7ZLRuV4Pdxok9+U1Kigv6jUtVJlijQkCCrZLBoO1CjMzXXzvCzkFR28Kl8=
