#!/usr/bin/env ruby
# frozen_string_literal: true

require 'optparse'

class Option
  DEFAULT_CONFIG_FILE = '.rubocop.yml'

  def initialize(argv)
    opt = OptionParser.new
    @override = false
    opt.on('-o', '--override') {|v| @override = true}
    @filename = opt.parse(argv)[0] || DEFAULT_CONFIG_FILE

  end
  attr_reader :override, :filename
end



def main
  opt = Option.new(ARGV)
end

main if __FILE__ == $0
